server:
  port: 8800

spring:
  application:
    name: "customer"
  data:
    mongodb:
      uri: mongodb://localhost:27017/fdCustomer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

customer:
  message: "this is default application properties"