server:
  port: 8801

spring:
  application:
    name: "deliverypartner"
  data:
    mongodb:
      uri: mongodb://localhost:27017/fdDeliveryPartner

deliverypartner:
  message: "this is prod application properties"