spring:
  application:
    name: Orders
  data:
    mongodb:
      uri: mongodb://localhost:27017/fdOrder
server:
  port: 8802

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

orders:
  message: "this is default application properties"