server:
  port: 8803
spring:
  application:
    name: restaurant
  data:
    mongodb:
      uri: mongodb://localhost:27017/fdRestaurant



restaurant:
  message: "this is restaurant application properties"